//! Run the daemon as a user service: a systemd user unit on Linux
//! (`~/.config/systemd/user/powerqueue.service`), a launchd agent on macOS
//! (`~/Library/LaunchAgents/dev.powerqueue.plist`).
//!
//! The generated file runs `<this binary> run` with the environment of the
//! shell that installed it (`PATH` and the variables in [`PASSTHROUGH_ENV`]),
//! restarts the daemon when it crashes but not after `powerqueue stop`, and
//! leaves the tmux server alone when the service stops: the daemon starts the
//! tmux server, so under systemd it lives in the service's cgroup and the
//! default `KillMode=control-group` would take every Claude session down with
//! the daemon. The unit sets `KillMode=process`; the agent sets
//! `AbandonProcessGroup`.
//!
//! Every operation shells out to `systemctl --user` / `launchctl` /
//! `loginctl` / `journalctl` with explicit arguments, and failures carry the
//! tool's stderr.

use std::collections::BTreeMap;
use std::fmt;
use std::path::{Path, PathBuf};
use std::process::{Command, Output, Stdio};

use anyhow::{Context as _, Result, bail};
use serde::Serialize;

use crate::config::Config;
use crate::paths::Paths;

/// Name of the systemd user unit.
pub const SYSTEMD_UNIT: &str = "powerqueue.service";
/// Label of the launchd agent.
pub const LAUNCHD_LABEL: &str = "dev.powerqueue";
/// First line of every generated file; marks it as ours.
pub const GENERATED_MARKER: &str = "Generated by `powerqueue service install`";

/// Variables copied from the installing shell into the service when set:
/// they decide where powerqueue keeps its files, which secrets backend it
/// uses, where tmux puts its socket (so `attach` from a shell finds the
/// daemon's sessions) and the locale the sessions run with. `PATH` is always
/// written. API keys are never copied (the file is world-readable).
pub const PASSTHROUGH_ENV: &[&str] = &[
    "POWERQUEUE_HOME",
    "POWERQUEUE_SECRETS",
    "XDG_CONFIG_HOME",
    "XDG_DATA_HOME",
    "XDG_STATE_HOME",
    "TMUX_TMPDIR",
    "LANG",
    "LC_ALL",
];

/// `PATH` written when the installing shell has none.
const FALLBACK_PATH: &str = "/usr/local/bin:/usr/bin:/bin";

/// The user-level service manager that runs the daemon.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, clap::ValueEnum)]
#[serde(rename_all = "lowercase")]
pub enum Manager {
    /// systemd user unit (Linux).
    Systemd,
    /// launchd agent (macOS).
    Launchd,
}

impl fmt::Display for Manager {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(match self {
            Manager::Systemd => "systemd",
            Manager::Launchd => "launchd",
        })
    }
}

impl Manager {
    /// launchd on macOS, systemd on other unixes when `systemctl` is on
    /// `PATH`. Fails elsewhere, naming what is missing.
    pub fn detect() -> Result<Self> {
        if cfg!(target_os = "macos") {
            return Ok(Manager::Launchd);
        }
        if which::which("systemctl").is_ok() {
            return Ok(Manager::Systemd);
        }
        bail!(
            "no supported service manager found (`systemctl` is not on PATH); run the daemon in tmux instead: \
             `tmux new-session -d -s pq-daemon 'powerqueue run'`"
        )
    }

    /// Where the unit (systemd) or agent plist (launchd) lives.
    pub fn unit_path(self) -> Result<PathBuf> {
        let home = home_dir()?;
        Ok(match self {
            Manager::Systemd => std::env::var_os("XDG_CONFIG_HOME")
                .filter(|v| !v.is_empty())
                .map(PathBuf::from)
                .unwrap_or_else(|| home.join(".config"))
                .join("systemd/user")
                .join(SYSTEMD_UNIT),
            Manager::Launchd => home.join("Library/LaunchAgents").join(format!("{LAUNCHD_LABEL}.plist")),
        })
    }

    /// The command that shows the service's own output.
    pub fn logs_command(self, paths: &Paths, lines: usize, follow: bool) -> Command {
        match self {
            Manager::Systemd => {
                let mut cmd = Command::new("journalctl");
                cmd.args(["--user", "-u", SYSTEMD_UNIT, "--no-pager", "-n", &lines.to_string()]);
                if follow {
                    cmd.arg("-f");
                }
                cmd
            }
            Manager::Launchd => {
                let mut cmd = Command::new("tail");
                cmd.args(["-n", &lines.to_string()]);
                if follow {
                    cmd.arg("-F");
                }
                cmd.arg(launchd_stdout(paths)).arg(launchd_stderr(paths));
                cmd
            }
        }
    }
}

/// `$HOME`, or the platform's idea of it.
fn home_dir() -> Result<PathBuf> {
    std::env::var_os("HOME")
        .filter(|v| !v.is_empty())
        .map(PathBuf::from)
        .or_else(|| directories::BaseDirs::new().map(|b| b.home_dir().to_path_buf()))
        .context("cannot determine the home directory (HOME is not set)")
}

/// launchd's capture of the daemon's stdout.
pub fn launchd_stdout(paths: &Paths) -> PathBuf {
    paths.logs_dir().join("launchd.out.log")
}

/// launchd's capture of the daemon's stderr.
pub fn launchd_stderr(paths: &Paths) -> PathBuf {
    paths.logs_dir().join("launchd.err.log")
}

/// What goes into a generated unit.
#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
pub struct ServiceSpec {
    /// The powerqueue executable the service runs.
    pub binary: PathBuf,
    /// Environment, in the order written (`PATH` first).
    pub env: Vec<(String, String)>,
    /// The daemon's working directory (the user's home).
    pub working_dir: PathBuf,
    /// Where launchd writes stdout/stderr (unused by systemd: the journal).
    pub stdout: PathBuf,
    pub stderr: PathBuf,
}

impl ServiceSpec {
    /// Build the spec from the running process: this executable, the current
    /// `PATH` (with the executable's directory added so sessions can run
    /// `powerqueue task complete`), the [`PASSTHROUGH_ENV`] variables that are
    /// set, `POWERQUEUE_HOME` from `home` (`--home`) when given, then `extra`
    /// (`--env KEY=VALUE`, which wins). Fails when the executable cannot be
    /// located.
    pub fn from_environment(paths: &Paths, home: Option<&Path>, extra: &[(String, String)]) -> Result<Self> {
        let binary = std::env::current_exe().context("locate the powerqueue executable")?;
        let binary = binary.canonicalize().unwrap_or(binary);
        let lookup = |k: &str| std::env::var(k).ok().filter(|v| !v.is_empty());
        let path = stable_path(lookup("PATH").as_deref().unwrap_or(FALLBACK_PATH));
        let path = with_dir_in_path(&path, binary.parent());
        let mut env: Vec<(String, String)> = vec![("PATH".to_string(), path)];
        for key in PASSTHROUGH_ENV {
            if let Some(v) = lookup(key) {
                env.push((key.to_string(), v));
            }
        }
        if let Some(home) = home {
            let abs = std::path::absolute(home).with_context(|| format!("resolve {}", home.display()))?;
            set_env(&mut env, "POWERQUEUE_HOME", &abs.to_string_lossy());
        }
        for (k, v) in extra {
            set_env(&mut env, k, v);
        }
        Ok(Self { binary, env, working_dir: home_dir()?, stdout: launchd_stdout(paths), stderr: launchd_stderr(paths) })
    }

    /// The value of `key` in [`ServiceSpec::env`].
    pub fn env_value(&self, key: &str) -> Option<&str> {
        self.env.iter().find(|(k, _)| k == key).map(|(_, v)| v.as_str())
    }

    /// The file contents for `manager`.
    pub fn render(&self, manager: Manager) -> String {
        match manager {
            Manager::Systemd => self.render_systemd(),
            Manager::Launchd => self.render_launchd(),
        }
    }

    fn render_systemd(&self) -> String {
        let mut out = String::new();
        out.push_str(&format!("# {GENERATED_MARKER} (powerqueue {}).\n", crate::VERSION));
        out.push_str("# Re-run it after moving the binary or changing PATH; `powerqueue service uninstall` removes it.\n");
        out.push_str("[Unit]\n");
        out.push_str("Description=powerqueue daemon (Linear -> Claude Code work queue)\n");
        out.push_str("Documentation=https://github.com/aleandros/powerqueue\n\n");
        out.push_str("[Service]\n");
        out.push_str("Type=simple\n");
        out.push_str(&format!("ExecStart={} run\n", systemd_quote(&self.binary.to_string_lossy())));
        // systemd's `~` is the user's home; this setting does not take quotes.
        out.push_str("WorkingDirectory=~\n");
        for (k, v) in &self.env {
            out.push_str(&format!("Environment={}\n", systemd_quote(&format!("{k}={v}"))));
        }
        out.push_str("# Restart after a crash, not after `powerqueue stop` (a clean exit).\n");
        out.push_str("Restart=on-failure\n");
        out.push_str("RestartSec=10\n");
        out.push_str("# The daemon starts the tmux server, so tmux and every Claude session live in this\n");
        out.push_str("# unit's cgroup: only signal the daemon, or a stop/restart would kill them all.\n");
        out.push_str("KillMode=process\n\n");
        out.push_str("[Install]\n");
        out.push_str("WantedBy=default.target\n");
        out
    }

    fn render_launchd(&self) -> String {
        let s = |v: &str| format!("<string>{}</string>", xml_escape(v));
        let mut out = String::new();
        out.push_str("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n");
        out.push_str(
            "<!DOCTYPE plist PUBLIC \"-//Apple//DTD PLIST 1.0//EN\" \"http://www.apple.com/DTDs/PropertyList-1.0.dtd\">\n",
        );
        out.push_str(&format!("<!-- {GENERATED_MARKER} (powerqueue {}).\n", crate::VERSION));
        out.push_str("     Re-run it after moving the binary or changing PATH; `powerqueue service uninstall` removes it. -->\n");
        out.push_str("<plist version=\"1.0\">\n<dict>\n");
        out.push_str(&format!("  <key>Label</key>{}\n", s(LAUNCHD_LABEL)));
        out.push_str("  <key>ProgramArguments</key>\n  <array>\n");
        out.push_str(&format!("    {}\n    {}\n", s(&self.binary.to_string_lossy()), s("run")));
        out.push_str("  </array>\n");
        out.push_str("  <key>EnvironmentVariables</key>\n  <dict>\n");
        for (k, v) in &self.env {
            out.push_str(&format!("    <key>{}</key>{}\n", xml_escape(k), s(v)));
        }
        out.push_str("  </dict>\n");
        out.push_str(&format!("  <key>WorkingDirectory</key>{}\n", s(&self.working_dir.to_string_lossy())));
        out.push_str("  <key>RunAtLoad</key><true/>\n");
        out.push_str("  <!-- Restart after a crash, not after `powerqueue stop` (a clean exit). -->\n");
        out.push_str("  <key>KeepAlive</key>\n  <dict>\n    <key>SuccessfulExit</key><false/>\n  </dict>\n");
        out.push_str("  <key>ThrottleInterval</key><integer>10</integer>\n");
        out.push_str("  <!-- Leave tmux and the Claude sessions running when the daemon exits. -->\n");
        out.push_str("  <key>AbandonProcessGroup</key><true/>\n");
        out.push_str(&format!("  <key>StandardOutPath</key>{}\n", s(&self.stdout.to_string_lossy())));
        out.push_str(&format!("  <key>StandardErrorPath</key>{}\n", s(&self.stderr.to_string_lossy())));
        out.push_str("</dict>\n</plist>\n");
        out
    }
}

/// Replace or append `key` in an ordered environment list.
fn set_env(env: &mut Vec<(String, String)>, key: &str, value: &str) {
    match env.iter_mut().find(|(k, _)| k == key) {
        Some(slot) => slot.1 = value.to_string(),
        None => env.push((key.to_string(), value.to_string())),
    }
}

/// `path` without duplicates, with entries that only live as long as the
/// installing shell replaced by what they point at. Version managers such as
/// fnm put a per-shell symlink under `$XDG_RUNTIME_DIR` / `/tmp`
/// (`fnm_multishells/<pid>_<ts>/bin`) on `PATH`; it disappears with the shell,
/// so the service would lose `node` (and with it `claude`). Following the
/// symlink one level gives the stable target (`~/.local/share/fnm/aliases/default/bin`).
fn stable_path(path: &str) -> String {
    let mut ephemeral_roots: Vec<PathBuf> = vec![PathBuf::from("/tmp"), PathBuf::from("/run/user")];
    for var in ["XDG_RUNTIME_DIR", "TMPDIR"] {
        if let Some(v) = std::env::var_os(var).filter(|v| !v.is_empty()) {
            ephemeral_roots.push(PathBuf::from(v));
        }
    }
    let mut seen: Vec<PathBuf> = Vec::new();
    for entry in std::env::split_paths(path) {
        if entry.as_os_str().is_empty() {
            continue;
        }
        let ephemeral = ephemeral_roots.iter().any(|r| entry.starts_with(r)) || entry.to_string_lossy().contains("multishells");
        let entry = if ephemeral { follow_first_symlink(&entry).unwrap_or(entry) } else { entry };
        if !seen.contains(&entry) {
            seen.push(entry);
        }
    }
    std::env::join_paths(&seen).map(|p| p.to_string_lossy().into_owned()).unwrap_or_else(|_| path.to_string())
}

/// `dir` with its deepest symlinked ancestor (or itself) replaced by the
/// link's absolute target; `None` when no component is a symlink.
fn follow_first_symlink(dir: &Path) -> Option<PathBuf> {
    for ancestor in dir.ancestors() {
        let meta = std::fs::symlink_metadata(ancestor).ok()?;
        if meta.file_type().is_symlink() {
            let target = std::fs::read_link(ancestor).ok()?;
            let target = if target.is_absolute() { target } else { ancestor.parent()?.join(target) };
            let rest = dir.strip_prefix(ancestor).ok()?;
            return Some(if rest.as_os_str().is_empty() { target } else { target.join(rest) });
        }
    }
    None
}

/// `path` with `dir` prepended unless it is already one of its entries.
fn with_dir_in_path(path: &str, dir: Option<&Path>) -> String {
    let Some(dir) = dir else { return path.to_string() };
    if std::env::split_paths(path).any(|p| p == dir) {
        return path.to_string();
    }
    let dir = dir.to_string_lossy();
    if path.is_empty() { dir.into_owned() } else { format!("{dir}:{path}") }
}

/// Parse `KEY=VALUE` (`--env`). Fails on a missing `=` or an empty key.
pub fn parse_env_assignment(s: &str) -> Result<(String, String)> {
    match s.split_once('=') {
        Some((k, v)) if !k.trim().is_empty() => Ok((k.trim().to_string(), v.to_string())),
        _ => bail!("`{s}` is not KEY=VALUE"),
    }
}

/// Quote one systemd unit word: `\` and `"` are backslash-escaped, `%`
/// (specifiers) and `$` (variable expansion) doubled.
fn systemd_quote(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('"');
    for ch in s.chars() {
        match ch {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '%' => out.push_str("%%"),
            '$' => out.push_str("$$"),
            c => out.push(c),
        }
    }
    out.push('"');
    out
}

/// Read the first word of a systemd value, undoing [`systemd_quote`] and
/// expanding `%h` (home). Returns the word and the rest of the line.
fn systemd_word<'a>(s: &'a str, home: &str) -> (String, &'a str) {
    let s = s.trim_start();
    let mut out = String::new();
    let mut chars = s.char_indices().peekable();
    let quoted = s.starts_with('"');
    if quoted {
        chars.next();
    }
    while let Some((i, ch)) = chars.next() {
        match ch {
            '"' if quoted => return (out, &s[i + 1..]),
            c if c.is_whitespace() && !quoted => return (out, &s[i..]),
            '\\' if quoted => {
                if let Some((_, next)) = chars.next() {
                    out.push(next);
                }
            }
            '%' => match chars.peek().map(|(_, c)| *c) {
                Some('%') => {
                    chars.next();
                    out.push('%');
                }
                Some('h') => {
                    chars.next();
                    out.push_str(home);
                }
                _ => out.push('%'),
            },
            '$' if chars.peek().map(|(_, c)| *c) == Some('$') => {
                chars.next();
                out.push('$');
            }
            c => out.push(c),
        }
    }
    (out, "")
}

fn xml_escape(s: &str) -> String {
    s.replace('&', "&amp;").replace('<', "&lt;").replace('>', "&gt;").replace('"', "&quot;")
}

fn xml_unescape(s: &str) -> String {
    s.replace("&lt;", "<").replace("&gt;", ">").replace("&quot;", "\"").replace("&apos;", "'").replace("&amp;", "&")
}

/// What an installed unit says, whether we generated it or the user wrote it
/// by hand (the README used to show one at the same path).
#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
pub struct InstalledUnit {
    pub path: PathBuf,
    #[serde(skip)]
    pub text: String,
    /// First word of `ExecStart` / `ProgramArguments`.
    pub binary: Option<PathBuf>,
    /// `Environment=` / `EnvironmentVariables`.
    pub env: BTreeMap<String, String>,
    /// `KillMode=process` (systemd) or `AbandonProcessGroup` (launchd): the
    /// tmux sessions survive a stop/restart of the service.
    pub keeps_sessions: bool,
    /// Written by `powerqueue service install`.
    pub generated: bool,
}

impl InstalledUnit {
    /// Read the unit at `manager.unit_path()`; `None` when there is none.
    pub fn load(manager: Manager) -> Result<Option<Self>> {
        let path = manager.unit_path()?;
        match std::fs::read_to_string(&path) {
            Ok(text) => Ok(Some(Self::parse(manager, path, text))),
            Err(e) if e.kind() == std::io::ErrorKind::NotFound => Ok(None),
            Err(e) => Err(e).with_context(|| format!("read {}", path.display())),
        }
    }

    /// Extract what powerqueue cares about from a unit's text. Lenient: a
    /// hand-written file yields whatever fields it has.
    pub fn parse(manager: Manager, path: PathBuf, text: String) -> Self {
        let home = home_dir().map(|h| h.to_string_lossy().into_owned()).unwrap_or_default();
        let mut unit = Self {
            path,
            binary: None,
            env: BTreeMap::new(),
            keeps_sessions: false,
            generated: text.contains(GENERATED_MARKER),
            text: String::new(),
        };
        match manager {
            Manager::Systemd => {
                for line in unit_lines(&text) {
                    let Some((key, value)) = line.split_once('=') else { continue };
                    match key.trim() {
                        "ExecStart" => {
                            // Strip systemd's exec prefixes (`-`, `@`, `+`, `!`, `:`).
                            let value = value.trim_start().trim_start_matches(['-', '@', '+', '!', ':']);
                            let (word, _) = systemd_word(value, &home);
                            unit.binary = Some(PathBuf::from(word));
                        }
                        "Environment" => {
                            let mut rest = value;
                            while !rest.trim().is_empty() {
                                let (word, tail) = systemd_word(rest, &home);
                                if let Some((k, v)) = word.split_once('=') {
                                    unit.env.insert(k.to_string(), v.to_string());
                                }
                                rest = tail;
                            }
                        }
                        "KillMode" => unit.keeps_sessions = value.trim() == "process",
                        _ => {}
                    }
                }
            }
            Manager::Launchd => {
                let program = plist_section(&text, "ProgramArguments", "</array>");
                unit.binary = program.and_then(|p| plist_strings(p).into_iter().next()).map(PathBuf::from);
                if let Some(dict) = plist_section(&text, "EnvironmentVariables", "</dict>") {
                    let keys = plist_tags(dict, "key");
                    let values = plist_strings(dict);
                    unit.env = keys.into_iter().zip(values).collect();
                }
                unit.keeps_sessions =
                    text.split("<key>AbandonProcessGroup</key>").nth(1).is_some_and(|t| t.trim_start().starts_with("<true/>"));
            }
        }
        unit.text = text;
        unit
    }

    /// Tools from `tools` that the unit's `PATH` does not resolve.
    pub fn missing_tools(&self, tools: &[String]) -> Vec<String> {
        let path = self.env.get("PATH").map(String::as_str).unwrap_or(FALLBACK_PATH);
        let cwd = home_dir().unwrap_or_else(|_| PathBuf::from("/"));
        tools.iter().filter(|t| which::which_in(t.as_str(), Some(path), &cwd).is_err()).cloned().collect()
    }
}

/// Something wrong with an installed unit, with the fix.
#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
pub struct UnitProblem {
    pub detail: String,
    pub hint: String,
}

/// Check an installed unit against this binary (`current_exe`) and the tools
/// the daemon needs (`tools`, see [`required_tools`]). Empty when healthy.
pub fn unit_problems(unit: &InstalledUnit, current_exe: Option<&Path>, tools: &[String]) -> Vec<UnitProblem> {
    let regenerate = "regenerate it with `powerqueue service install --force`".to_string();
    let mut out = Vec::new();
    if !unit.keeps_sessions {
        out.push(UnitProblem {
            detail: "stopping or restarting the service kills tmux and every running session \
                     (the unit has no `KillMode=process` / `AbandonProcessGroup`)"
                .to_string(),
            hint: regenerate.clone(),
        });
    }
    match &unit.binary {
        None => {
            out.push(UnitProblem { detail: "the unit does not say which binary it runs".to_string(), hint: regenerate.clone() })
        }
        Some(b) if !b.exists() => out.push(UnitProblem {
            detail: format!("it runs {}, which does not exist", b.display()),
            hint: format!("{regenerate} from the powerqueue you want to run"),
        }),
        Some(b) => {
            let canon = |p: &Path| p.canonicalize().unwrap_or_else(|_| p.to_path_buf());
            if let Some(exe) = current_exe
                && canon(b) != canon(exe)
            {
                out.push(UnitProblem {
                    detail: format!("it runs {}, not this binary ({})", b.display(), exe.display()),
                    hint: format!("{regenerate} if this is the powerqueue you want the service to run"),
                });
            }
        }
    }
    let missing = unit.missing_tools(tools);
    if !missing.is_empty() {
        out.push(UnitProblem {
            detail: format!("its PATH cannot find {}", missing.join(", ")),
            hint: "run `powerqueue service install --force` from a shell where they are on PATH, \
                   or add `--env PATH=...`"
                .to_string(),
        });
    }
    out
}

/// Non-comment lines of a systemd unit with continuation lines joined.
fn unit_lines(text: &str) -> Vec<String> {
    let mut out = Vec::new();
    let mut current = String::new();
    for raw in text.lines() {
        let line = raw.trim();
        if current.is_empty() && (line.starts_with('#') || line.starts_with(';')) {
            continue;
        }
        if let Some(stripped) = line.strip_suffix('\\') {
            current.push_str(stripped);
            current.push(' ');
            continue;
        }
        current.push_str(line);
        out.push(std::mem::take(&mut current));
    }
    if !current.is_empty() {
        out.push(current);
    }
    out
}

/// The plist text after `<key>{key}</key>` up to the first `end`.
fn plist_section<'a>(text: &'a str, key: &str, end: &str) -> Option<&'a str> {
    let start = text.find(&format!("<key>{key}</key>"))? + key.len() + 11;
    let rest = &text[start..];
    let stop = rest.find(end).map(|i| i + end.len()).unwrap_or(rest.len());
    Some(&rest[..stop])
}

/// Contents of every `<tag>...</tag>` in `text`, unescaped.
fn plist_tags(text: &str, tag: &str) -> Vec<String> {
    let open = format!("<{tag}>");
    let close = format!("</{tag}>");
    let mut out = Vec::new();
    let mut rest = text;
    while let Some(i) = rest.find(&open) {
        rest = &rest[i + open.len()..];
        let Some(j) = rest.find(&close) else { break };
        out.push(xml_unescape(&rest[..j]));
        rest = &rest[j + close.len()..];
    }
    out
}

fn plist_strings(text: &str) -> Vec<String> {
    plist_tags(text, "string")
}

/// The tools the daemon runs: git, tmux, the CLI of every enabled provider,
/// and `gh` when the PR watcher is on.
pub fn required_tools(cfg: &Config) -> Vec<String> {
    let mut tools = vec!["git".to_string(), cfg.tmux.binary.clone()];
    for p in cfg.budget.enabled_providers_in_order() {
        // A command template (`docker exec … claude`) needs its program, not the whole line.
        tools.push(crate::session::program_of(&cfg.launch_settings(p).binary));
    }
    if cfg.scheduler.pr_poll_secs > 0 {
        tools.push(cfg.scheduler.gh_binary.clone());
    }
    tools.retain(|t| !t.trim().is_empty());
    tools.dedup();
    tools
}

/// What the service manager reports right now.
#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
pub struct ServiceState {
    pub manager: Manager,
    /// The manager knows the unit (systemd: loaded; launchd: bootstrapped).
    pub loaded: bool,
    /// Starts at login (systemd: enabled; launchd: loaded).
    pub enabled: bool,
    pub running: bool,
    pub pid: Option<u32>,
    /// The manager's own words (`active/running`, `state = running`, ...).
    pub detail: String,
    /// systemd only: user lingering, which keeps the service up after logout.
    pub linger: Option<bool>,
}

/// Ask the service manager about the powerqueue service. Fails when the
/// manager itself cannot be run (e.g. `systemctl --user` has no user bus).
pub fn query(manager: Manager) -> Result<ServiceState> {
    match manager {
        Manager::Systemd => {
            let out = run(
                "systemctl",
                &["--user", "show", SYSTEMD_UNIT, "-p", "LoadState,ActiveState,SubState,MainPID,UnitFileState"],
            )?;
            let props: BTreeMap<&str, &str> = out.lines().filter_map(|l| l.split_once('=')).collect();
            let get = |k: &str| props.get(k).copied().unwrap_or("");
            let active = get("ActiveState");
            Ok(ServiceState {
                manager,
                loaded: get("LoadState") == "loaded",
                enabled: matches!(get("UnitFileState"), "enabled" | "enabled-runtime" | "linked"),
                running: matches!(active, "active" | "activating" | "reloading"),
                pid: get("MainPID").parse().ok().filter(|p| *p != 0),
                detail: format!("{active}/{}", get("SubState")),
                linger: linger(),
            })
        }
        Manager::Launchd => {
            let target = launchd_target()?;
            let out = Command::new("launchctl")
                .args(["print", &target])
                .stdin(Stdio::null())
                .output()
                .context("run `launchctl print`")?;
            if !out.status.success() {
                return Ok(ServiceState {
                    manager,
                    loaded: false,
                    enabled: false,
                    running: false,
                    pid: None,
                    detail: "not loaded".to_string(),
                    linger: None,
                });
            }
            let text = String::from_utf8_lossy(&out.stdout);
            let field = |name: &str| {
                text.lines()
                    .map(str::trim)
                    .find_map(|l| l.strip_prefix(name)?.trim_start().strip_prefix('=').map(|v| v.trim().to_string()))
            };
            let state = field("state").unwrap_or_else(|| "unknown".to_string());
            Ok(ServiceState {
                manager,
                loaded: true,
                enabled: true,
                running: state == "running",
                pid: field("pid").and_then(|p| p.parse().ok()),
                detail: format!("state = {state}"),
                linger: None,
            })
        }
    }
}

/// `loginctl show-user <me> -p Linger`; `None` when it cannot be asked.
fn linger() -> Option<bool> {
    let user = current_user().ok()?;
    let out =
        Command::new("loginctl").args(["show-user", &user, "-p", "Linger", "--value"]).stdin(Stdio::null()).output().ok()?;
    if !out.status.success() {
        // No session for the user yet: loginctl reports an error, lingering is off.
        return Some(false);
    }
    Some(String::from_utf8_lossy(&out.stdout).trim() == "yes")
}

/// `loginctl enable-linger <me>`: the user's services keep running after the
/// last session ends and start at boot.
pub fn enable_linger() -> Result<()> {
    let user = current_user()?;
    run("loginctl", &["enable-linger", &user]).map(|_| ())
}

fn current_user() -> Result<String> {
    if let Some(u) = std::env::var("USER").ok().filter(|u| !u.is_empty()) {
        return Ok(u);
    }
    Ok(run("id", &["-un"])?.trim().to_string())
}

/// `gui/<uid>/dev.powerqueue`.
fn launchd_target() -> Result<String> {
    Ok(format!("{}/{LAUNCHD_LABEL}", launchd_domain()?))
}

/// `gui/<uid>`.
fn launchd_domain() -> Result<String> {
    Ok(format!("gui/{}", run("id", &["-u"])?.trim()))
}

/// Make the manager pick up a freshly written unit and enable it; with
/// `start`, also start it. Does not restart a running instance.
pub fn activate(manager: Manager, start: bool) -> Result<()> {
    match manager {
        Manager::Systemd => {
            run("systemctl", &["--user", "daemon-reload"])?;
            let mut args = vec!["--user", "enable"];
            if start {
                args.push("--now");
            }
            args.push(SYSTEMD_UNIT);
            run("systemctl", &args).map(|_| ())
        }
        Manager::Launchd => {
            // RunAtLoad: bootstrapping starts it. Without `start` the agent
            // loads at the next login.
            if start {
                let path = manager.unit_path()?;
                run("launchctl", &["bootstrap", &launchd_domain()?, &path.to_string_lossy()]).map(|_| ())
            } else {
                Ok(())
            }
        }
    }
}

/// Apply a rewritten unit to a service that is already running and restart
/// it so the new settings take effect.
pub fn reload_and_restart(manager: Manager) -> Result<()> {
    match manager {
        Manager::Systemd => {
            run("systemctl", &["--user", "daemon-reload"])?;
            run("systemctl", &["--user", "enable", SYSTEMD_UNIT])?;
            restart(manager)
        }
        Manager::Launchd => {
            let _ = run("launchctl", &["bootout", &launchd_target()?]);
            activate(manager, true)
        }
    }
}

/// Start the service (loading the launchd agent first when needed).
pub fn start(manager: Manager) -> Result<()> {
    match manager {
        Manager::Systemd => run("systemctl", &["--user", "start", SYSTEMD_UNIT]).map(|_| ()),
        Manager::Launchd => {
            if !query(manager)?.loaded {
                return activate(manager, true);
            }
            run("launchctl", &["kickstart", &launchd_target()?]).map(|_| ())
        }
    }
}

/// Stop the daemon (SIGTERM; it exits after its current tick and is not
/// restarted). tmux sessions survive when the unit keeps them.
pub fn stop(manager: Manager) -> Result<()> {
    match manager {
        Manager::Systemd => run("systemctl", &["--user", "stop", SYSTEMD_UNIT]).map(|_| ()),
        Manager::Launchd => run("launchctl", &["kill", "SIGTERM", &launchd_target()?]).map(|_| ()),
    }
}

/// Restart the daemon (start it when stopped).
pub fn restart(manager: Manager) -> Result<()> {
    match manager {
        Manager::Systemd => run("systemctl", &["--user", "restart", SYSTEMD_UNIT]).map(|_| ()),
        Manager::Launchd => {
            if !query(manager)?.loaded {
                return activate(manager, true);
            }
            run("launchctl", &["kickstart", "-k", &launchd_target()?]).map(|_| ())
        }
    }
}

/// Stop the service, disable it and unload it (the unit file is left for the
/// caller to remove).
pub fn deactivate(manager: Manager) -> Result<()> {
    match manager {
        Manager::Systemd => {
            run("systemctl", &["--user", "disable", "--now", SYSTEMD_UNIT])?;
            Ok(())
        }
        Manager::Launchd => {
            if query(manager)?.loaded {
                run("launchctl", &["bootout", &launchd_target()?])?;
            }
            Ok(())
        }
    }
}

/// Tell systemd the unit file is gone (no-op for launchd).
pub fn forget(manager: Manager) -> Result<()> {
    match manager {
        Manager::Systemd => run("systemctl", &["--user", "daemon-reload"]).map(|_| ()),
        Manager::Launchd => Ok(()),
    }
}

/// Run `program args`, returning stdout; fails with the command line and
/// stderr when it cannot start or exits non-zero.
fn run(program: &str, args: &[&str]) -> Result<String> {
    let cmdline = format!("{program} {}", args.join(" "));
    let out: Output =
        Command::new(program).args(args).stdin(Stdio::null()).output().with_context(|| format!("run `{cmdline}`"))?;
    if !out.status.success() {
        let stderr = String::from_utf8_lossy(&out.stderr);
        let stdout = String::from_utf8_lossy(&out.stdout);
        let msg = if stderr.trim().is_empty() { stdout.trim().to_string() } else { stderr.trim().to_string() };
        bail!("`{cmdline}` failed ({}): {msg}", out.status);
    }
    Ok(String::from_utf8_lossy(&out.stdout).into_owned())
}

#[cfg(test)]
mod tests {
    use super::*;

    fn spec() -> ServiceSpec {
        ServiceSpec {
            binary: PathBuf::from("/opt/pq bin/powerqueue"),
            env: vec![
                ("PATH".to_string(), "/opt/pq bin:/usr/bin:/bin".to_string()),
                ("POWERQUEUE_HOME".to_string(), "/srv/pq 100%".to_string()),
                ("WEIRD".to_string(), "a\"b$c\\d<&>".to_string()),
            ],
            working_dir: PathBuf::from("/home/me"),
            stdout: PathBuf::from("/home/me/.local/state/powerqueue/logs/launchd.out.log"),
            stderr: PathBuf::from("/home/me/.local/state/powerqueue/logs/launchd.err.log"),
        }
    }

    #[test]
    fn systemd_unit_round_trips_and_keeps_sessions() {
        let text = spec().render(Manager::Systemd);
        assert!(text.contains("KillMode=process"), "{text}");
        assert!(text.contains("Restart=on-failure"));
        assert!(text.contains("ExecStart=\"/opt/pq bin/powerqueue\" run"));
        assert!(text.contains("Environment=\"POWERQUEUE_HOME=/srv/pq 100%%\""));
        let unit = InstalledUnit::parse(Manager::Systemd, PathBuf::from("u"), text);
        assert!(unit.generated && unit.keeps_sessions);
        assert_eq!(unit.binary, Some(PathBuf::from("/opt/pq bin/powerqueue")));
        assert_eq!(unit.env.get("POWERQUEUE_HOME").map(String::as_str), Some("/srv/pq 100%"));
        assert_eq!(unit.env.get("WEIRD").map(String::as_str), Some("a\"b$c\\d<&>"));
        assert_eq!(unit.env.get("PATH").map(String::as_str), Some("/opt/pq bin:/usr/bin:/bin"));
    }

    #[test]
    fn launchd_plist_round_trips_and_keeps_sessions() {
        let text = spec().render(Manager::Launchd);
        assert!(text.contains("<key>AbandonProcessGroup</key><true/>"), "{text}");
        assert!(text.contains("<key>SuccessfulExit</key><false/>"));
        let unit = InstalledUnit::parse(Manager::Launchd, PathBuf::from("p"), text);
        assert!(unit.generated && unit.keeps_sessions);
        assert_eq!(unit.binary, Some(PathBuf::from("/opt/pq bin/powerqueue")));
        assert_eq!(unit.env.get("WEIRD").map(String::as_str), Some("a\"b$c\\d<&>"));
        assert_eq!(unit.env.len(), 3);
    }

    #[test]
    fn hand_written_readme_unit_is_understood() {
        // The unit the README showed before `service install` existed.
        let text = "[Unit]\nDescription=powerqueue daemon\n\n[Service]\nExecStart=%h/.cargo/bin/powerqueue run\n\
                    Restart=on-failure\nEnvironment=PATH=%h/.cargo/bin:/usr/local/bin:/usr/bin:/bin\n\n\
                    [Install]\nWantedBy=default.target\n";
        let unit = InstalledUnit::parse(Manager::Systemd, PathBuf::from("u"), text.to_string());
        assert!(!unit.generated);
        assert!(!unit.keeps_sessions, "no KillMode=process: a stop kills the tmux sessions");
        let home = home_dir().unwrap();
        assert_eq!(unit.binary, Some(home.join(".cargo/bin/powerqueue")));
        assert!(unit.env["PATH"].starts_with(&*home.to_string_lossy()));
    }

    #[test]
    fn hand_written_plist_without_abandon_does_not_keep_sessions() {
        let text = "<plist><dict><key>Label</key><string>dev.powerqueue</string><key>ProgramArguments</key><array>\
                    <string>/usr/local/bin/powerqueue</string><string>run</string></array>\
                    <key>AbandonProcessGroup</key><false/></dict></plist>";
        let unit = InstalledUnit::parse(Manager::Launchd, PathBuf::from("p"), text.to_string());
        assert_eq!(unit.binary, Some(PathBuf::from("/usr/local/bin/powerqueue")));
        assert!(!unit.keeps_sessions);
        assert!(unit.env.is_empty());
    }

    #[test]
    fn environment_spec_adds_binary_dir_and_overrides() {
        assert_eq!(with_dir_in_path("/usr/bin:/bin", Some(Path::new("/opt/pq"))), "/opt/pq:/usr/bin:/bin");
        assert_eq!(with_dir_in_path("/opt/pq:/bin", Some(Path::new("/opt/pq"))), "/opt/pq:/bin");
        let mut env = vec![("PATH".to_string(), "/bin".to_string())];
        set_env(&mut env, "PATH", "/usr/bin");
        set_env(&mut env, "FOO", "1");
        assert_eq!(env, vec![("PATH".to_string(), "/usr/bin".to_string()), ("FOO".to_string(), "1".to_string())]);
        assert_eq!(parse_env_assignment("A=b=c").unwrap(), ("A".to_string(), "b=c".to_string()));
        assert!(parse_env_assignment("nope").is_err());
        assert!(parse_env_assignment("=x").is_err());
    }

    #[cfg(unix)]
    #[test]
    fn ephemeral_path_entries_are_followed_and_duplicates_dropped() {
        let dir = tempfile::tempdir().unwrap();
        let stable = dir.path().join("aliases/default");
        std::fs::create_dir_all(stable.join("bin")).unwrap();
        let shells = dir.path().join("fnm_multishells");
        std::fs::create_dir_all(&shells).unwrap();
        let link = shells.join("123_456");
        std::os::unix::fs::symlink(&stable, &link).unwrap();
        let path = format!("/usr/bin:{}:/bin:/usr/bin", link.join("bin").display());
        let want = format!("/usr/bin:{}:/bin", stable.join("bin").display());
        assert_eq!(stable_path(&path), want);
        assert_eq!(follow_first_symlink(Path::new("/usr/bin")), None);
    }

    #[test]
    fn missing_tools_uses_the_unit_path() {
        let dir = tempfile::tempdir().unwrap();
        let tool = dir.path().join("mytool");
        std::fs::write(&tool, "#!/bin/sh\n").unwrap();
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            std::fs::set_permissions(&tool, std::fs::Permissions::from_mode(0o755)).unwrap();
        }
        let mut unit = InstalledUnit::parse(Manager::Systemd, PathBuf::from("u"), String::new());
        unit.env.insert("PATH".to_string(), dir.path().to_string_lossy().into_owned());
        let missing = unit.missing_tools(&["mytool".to_string(), "definitely-not-a-tool-pq".to_string()]);
        assert_eq!(missing, vec!["definitely-not-a-tool-pq".to_string()]);
    }
}
